### ISSUE TITLE
Class 'Symfony\Component\Console\Application' not found

### ISSUE THREAD

**Issue by tim0991** [ant-vel/Installer#3]
I run `composer global require "antvel/installer"` successed
and i put `antvel` shell script into $PATH, after i run `antvel` i got this error

**Comment by gocanto** [comment]
will fix it on Sat. I need to update laravel on this pakg.

**Comment by jimmywshee** [comment]
Hi gocanto, I also facing same issue here.. unable to install

**Comment by gocanto** [comment]
yes, I need to work on the installer update but I have been pretty busy lately. I will try to work on it this next weekend. but you can send a PR if u want

**Comment by gocanto** [comment]
I was not able to reproduce this error. I have been trying to do but nothing appeared :(

**Comment by diccn** [comment]
Hi gocanto, I also facing same issue here.. unable to install

**Comment by winnerawan** [comment]
clone this repo
```bash
git clone https://github.com/ant-vel/Installer
```
enter to directory
```bash
cd Installer
```
```bash
composer install
```
and then
```bash
chmod +x antvel
```
then
```bash
./antvel install
```
