### ISSUE TITLE
Antvel command not found

### ISSUE THREAD

**Issue by liveweb22** [ant-vel/Installer#5]
constantinalin871@server-vm:~/.composer/vendor/bin$ ls
antvel
constantinalin871@server-vm:~/.composer/vendor/bin$ antvel install
-bash: antvel: command not found
constantinalin871@server-vm:~/.composer/vendor/bin$

**Comment by gocanto** [comment]
I will update the installer soon. Also, PRs are welcome if you are keen :dancer:

**Comment by gocanto** [comment]
Here is a woek around
https://github.com/ant-vel/Installer/issues/3
