### ISSUE TITLE
antvel install have a problem. 'Symfony\Component\Console\Application' not found

### ISSUE THREAD

**Issue by jasonLaw1015** [ant-vel/Installer#9]
￼antvel install
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Application' not found in /Users/jasonlaw/.composer/vendor/antvel/installer/antvel:9
Stack trace:
#0 {main}
  thrown in /Users/jasonlaw/.composer/vendor/antvel/installer/antvel on line 9

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Application' not found in /Users/jasonlaw/.composer/vendor/antvel/installer/antvel:9
Stack trace:
#0 {main}
  thrown in /Users/jasonlaw/.composer/vendor/antvel/installer/antvel on line 9

**Comment by freshcoderchan** [comment]
Hi, @jasonLaw1015 
I have same issue now.
Have you fixed?

**Comment by gocanto** [comment]
Here is a work around
https://github.com/ant-vel/Installer/issues/3
